### ISSUE TITLE
Duplicate agents registered

### ISSUE THREAD

**Issue by LFBernardo** [BinaryDefense/auto-ossec#3]
Hi All, 

I have started rolling out the agents to a large number of end points and I have noticed a little bug that could potentially cause quite a bit of work. 

We deploy the agent via an automation tool. This then runs the installation at a specific time for the end  points designated. What then happens is a flood of registrations coming in at a specific time, the server script then passes it on as quickly as it can process them causing duplicate entries of agent ID's. Would it  be possible to make it queue connections limiting them so that the duplication is eliminated? 

As a short term workaround I am scripting a sequential installation, this will make the roll out of my 4500 agents quite a bit longer. 

Thanks,

Louis

**Comment by branchnetconsulting** [comment]
I had this same problem, so I forked the project and added a mechanism to queue auto-ossec registration requests.  See: https://github.com/branchnetconsulting/auto-ossec

Kevin

**Comment by trustedsec** [comment]
I'll have this added within the next couple of days - just released a large version that adds a lot of functionality, \* ip addresses and more, will incorporate this into it shortly.

**Comment by trustedsec** [comment]
I've just released version 1.6 which I spent a significant amount of time on from everything for python 2 and 3 support as well as an entire queue system. Everything now works by staging everything in memory then using it when the queue becomes available. I also rewrote the lock so it no longer has a file based lock and is a global lock variable. Should address all of these and be much more efficient since its not file based.

Thanks for the report - appreciated!
